### ISSUE TITLE
Query Lockbox API for user data

### ISSUE THREAD

**Issue by AJCStriker** [23rd-gaming-division/avatar-creator#1]
Should consume a REST JSON API that has the following schema:

( param: id = SteamID of requested user )
GET /User/:id 

Response: 
```
{
  "bio": {
    "name": {
      "first": "Alex",
      "last": "Striker"
    }
  },
  "service": {
    "rank": {
      "abbreviation": "CPT",
      "title": "Captain"
    }
  }
}
```

**Comment by mrgwilliam** [comment]
Method added via route /avatar-creator/user/:steamid
- Now pushed to live test site at services.23rd-div.com
https://services.23rd-div.com/avatar-creator/create/Guillermo/Rodriguez/Captain/CPT (URL method)
https://services.23rd-div.com/avatar-creator/user/:steamid (queries lockbox at https://lockbox.23rd-div.com/User/:steamid)
